In [1]:
import pandas as pd

fish = pd.read_csv('https://bit.ly/fish_csv_data')
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [3]:
fish.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Species   159 non-null    object 
 1   Weight    159 non-null    float64
 2   Length    159 non-null    float64
 3   Diagonal  159 non-null    float64
 4   Height    159 non-null    float64
 5   Width     159 non-null    float64
dtypes: float64(5), object(1)
memory usage: 7.6+ KB


In [4]:
fish.Species.unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [5]:
fish.columns

Index(['Species', 'Weight', 'Length', 'Diagonal', 'Height', 'Width'], dtype='object')

In [6]:
fish['Species']

0      Bream
1      Bream
2      Bream
3      Bream
4      Bream
       ...  
154    Smelt
155    Smelt
156    Smelt
157    Smelt
158    Smelt
Name: Species, Length: 159, dtype: object

In [7]:
fish[['Species', 'Weight']]


Species  Weight
0     Bream   242.0
1     Bream   290.0
2     Bream   340.0
3     Bream   363.0
4     Bream   430.0
..      ...     ...
154   Smelt    12.2
155   Smelt    13.4
156   Smelt    12.2
157   Smelt    19.7
158   Smelt    19.9

[159 rows x 2 columns]

In [8]:
fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].values

array([[2.42000e+02, 2.54000e+01, 3.00000e+01, 1.15200e+01, 4.02000e+00],
       [2.90000e+02, 2.63000e+01, 3.12000e+01, 1.24800e+01, 4.30560e+00],
       [3.40000e+02, 2.65000e+01, 3.11000e+01, 1.23778e+01, 4.69610e+00],
       [3.63000e+02, 2.90000e+01, 3.35000e+01, 1.27300e+01, 4.45550e+00],
       [4.30000e+02, 2.90000e+01, 3.40000e+01, 1.24440e+01, 5.13400e+00],
       [4.50000e+02, 2.97000e+01, 3.47000e+01, 1.36024e+01, 4.92740e+00],
       [5.00000e+02, 2.97000e+01, 3.45000e+01, 1.41795e+01, 5.27850e+00],
       [3.90000e+02, 3.00000e+01, 3.50000e+01, 1.26700e+01, 4.69000e+00],
       [4.50000e+02, 3.00000e+01, 3.51000e+01, 1.40049e+01, 4.84380e+00],
       [5.00000e+02, 3.07000e+01, 3.62000e+01, 1.42266e+01, 4.95940e+00],
       [4.75000e+02, 3.10000e+01, 3.62000e+01, 1.42628e+01, 5.10420e+00],
       [5.00000e+02, 3.10000e+01, 3.62000e+01, 1.43714e+01, 4.81460e+00],
       [5.00000e+02, 3.15000e+01, 3.64000e+01, 1.37592e+01, 4.36800e+00],
       [3.40000e+02, 3.20000e+01, 3.73

In [9]:
fish_input = fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].values

In [10]:
fish_target = fish['Species'].to_numpy()

In [11]:
fish_target

array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Whitefish',
       'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perc

In [12]:
from sklearn.model_selection import train_test_split

In [17]:
train_input, test_input, train_target, test_target = train_test_split(
    fish_input, fish_target, shuffle=True, random_state=42)

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()

In [21]:
sc.fit(train_input)
train_scaled = sc.transform(train_input)
test_scaled = sc.transform(test_input)

## 로지스틱 회귀로 이진 분류 수행하기

In [28]:
fish.Species.value_counts()

Species
Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: count, dtype: int64

In [32]:
train_target

array(['Bream', 'Pike', 'Smelt', 'Perch', 'Parkki', 'Roach', 'Perch',
       'Bream', 'Perch', 'Perch', 'Perch', 'Bream', 'Perch', 'Parkki',
       'Perch', 'Bream', 'Smelt', 'Perch', 'Roach', 'Bream', 'Pike',
       'Bream', 'Pike', 'Perch', 'Parkki', 'Bream', 'Perch', 'Pike',
       'Bream', 'Perch', 'Parkki', 'Roach', 'Perch', 'Bream', 'Roach',
       'Perch', 'Bream', 'Bream', 'Perch', 'Perch', 'Roach', 'Pike',
       'Perch', 'Smelt', 'Pike', 'Roach', 'Perch', 'Parkki', 'Perch',
       'Bream', 'Perch', 'Smelt', 'Perch', 'Parkki', 'Smelt', 'Perch',
       'Perch', 'Roach', 'Bream', 'Perch', 'Perch', 'Roach', 'Roach',
       'Perch', 'Perch', 'Bream', 'Roach', 'Bream', 'Roach', 'Parkki',
       'Perch', 'Perch', 'Perch', 'Perch', 'Pike', 'Pike', 'Perch',
       'Bream', 'Perch', 'Bream', 'Whitefish', 'Pike', 'Bream', 'Bream',
       'Roach', 'Perch', 'Pike', 'Bream', 'Pike', 'Parkki', 'Roach',
       'Perch', 'Roach', 'Smelt', 'Whitefish', 'Roach', 'Perch', 'Bream',
       'Whitefi

In [34]:
train_scaled[(train_target == 'Bream') | (train_target == 'Smelt')]

array([[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672],
       [-1.0858536 , -1.68646987, -1.70848587, -1.70159849, -2.0044758 ],
       [ 0.63818253,  0.56257661,  0.73223951,  1.64473401,  0.50705737],
       [ 0.30041219,  0.23459067,  0.42823457,  1.36042157,  0.22329758],
       [ 0.9027693 ,  0.70314202,  0.88858491,  1.89027545,  0.85537174],
       [-1.0824759 , -1.61150165, -1.62162731, -1.7000674 , -1.92815631],
       [ 0.10337949,  0.04717013,  0.23714575,  0.88445197,  0.41799764],
       [ 1.49668216,  1.03112796,  1.21864741,  2.44274986,  1.40289707],
       [ 0.23004337,  0.23459067,  0.42823457,  1.3336029 ,  0.39983213],
       [-0.42579405, -0.29018684, -0.11028847,  0.65627104, -0.26107519],
       [ 1.28557569,  0.70314202,  0.89727076,  1.98228866,  1.06683526],
       [ 0.93373158,  0.60943175,  0.83646978,  1.85150445,  0.97832415],
       [ 0.80706771,  0.60943175,  0.81041221,  1.63137406,  1.0255057 ],
       [-1.07262426, -1.52716241, -1.5

In [44]:
bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]

In [45]:
type(train_bream_smelt)

numpy.ndarray

In [46]:
train_bream_smelt[:5, :]

array([[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672],
       [-1.0858536 , -1.68646987, -1.70848587, -1.70159849, -2.0044758 ],
       [ 0.63818253,  0.56257661,  0.73223951,  1.64473401,  0.50705737],
       [ 0.30041219,  0.23459067,  0.42823457,  1.36042157,  0.22329758],
       [ 0.9027693 ,  0.70314202,  0.88858491,  1.89027545,  0.85537174]])

In [47]:
target_bream_smelt

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream', 'Smelt', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Smelt',
       'Bream', 'Smelt', 'Smelt', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Smelt', 'Bream', 'Smelt',
       'Smelt', 'Bream', 'Smelt', 'Bream', 'Bream'], dtype=object)

In [48]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)

LogisticRegression()

In [50]:
lr.classes_

array(['Bream', 'Smelt'], dtype=object)

In [51]:
train_bream_smelt[:5]

array([[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672],
       [-1.0858536 , -1.68646987, -1.70848587, -1.70159849, -2.0044758 ],
       [ 0.63818253,  0.56257661,  0.73223951,  1.64473401,  0.50705737],
       [ 0.30041219,  0.23459067,  0.42823457,  1.36042157,  0.22329758],
       [ 0.9027693 ,  0.70314202,  0.88858491,  1.89027545,  0.85537174]])

In [52]:
lr.predict(train_bream_smelt[:5])

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream'], dtype=object)

In [53]:
target_bream_smelt[:5]

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream'], dtype=object)

In [56]:
print(lr.predict_proba(train_bream_smelt[:5]))

[[0.99760007 0.00239993]
 [0.02737325 0.97262675]
 [0.99486386 0.00513614]
 [0.98585047 0.01414953]
 [0.99767419 0.00232581]]


In [54]:
lr.predict(train_bream_smelt[:])

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream', 'Smelt', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Smelt',
       'Bream', 'Smelt', 'Smelt', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Smelt', 'Bream', 'Smelt',
       'Smelt', 'Bream', 'Smelt', 'Bream', 'Bream'], dtype=object)

In [55]:
target_bream_smelt[:]

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream', 'Smelt', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Smelt',
       'Bream', 'Smelt', 'Smelt', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Smelt', 'Bream', 'Smelt',
       'Smelt', 'Bream', 'Smelt', 'Bream', 'Bream'], dtype=object)

In [58]:
fish.columns

Index(['Species', 'Weight', 'Length', 'Diagonal', 'Height', 'Width'], dtype='object')

In [57]:
print(lr.coef_, lr.intercept_)

[[-0.40451732 -0.57582787 -0.66248158 -1.01329614 -0.73123131]] [-2.16172774]


In [59]:
# z = lr.coef_[0][0] * Weight + lr.coef_[0][1] * Length + lr.coef_[0][2] * Digonal +
#     lr.coef_[0][3] * Height + lr.coef_[0][4] * Width + lr.intercept_

In [62]:
train_bream_smelt[:5][0][0]

0.919657820086829

In [63]:
[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672]

[0.91965782, 0.60943175, 0.81041221, 1.85194896, 1.00075672]

In [64]:
# z = lr.coef_[0][0] * train_bream_smelt[:5][0][0] + 
#     lr.coef_[0][1] * train_bream_smelt[:5][0][1] + 
#     lr.coef_[0][2] * train_bream_smelt[:5][0][2] +
#     lr.coef_[0][3] * train_bream_smelt[:5][0][3] + 
#     lr.coef_[0][4] * train_bream_smelt[:5][0][4] + lr.intercept_

In [66]:
z = lr.coef_[0][0] * train_bream_smelt[:5][0][0] + lr.coef_[0][1] * train_bream_smelt[:5][0][1] + lr.coef_[0][2] * train_bream_smelt[:5][0][2] + lr.coef_[0][3] * train_bream_smelt[:5][0][3] + lr.coef_[0][4] * train_bream_smelt[:5][0][4] + lr.intercept_

In [67]:
z

array([-6.02991358])

In [68]:
lr.decision_function(train_bream_smelt[:5])

array([-6.02991358,  3.57043428, -5.26630496, -4.24382314, -6.06135688])

In [69]:
import numpy as np

In [72]:
1 / (1 + np.exp(-(lr.decision_function(train_bream_smelt[:5]))))

array([0.00239993, 0.97262675, 0.00513614, 0.01414953, 0.00232581])

## 로지스틱 회귀로 다중 분류 수행하기

In [73]:
lr = LogisticRegression(C=20, max_iter=100)

In [74]:
lr.fit(train_scaled, train_target)

LogisticRegression(C=20)

In [75]:
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.9327731092436975
0.925


In [76]:
lr2 = LogisticRegression(C=20, max_iter=1000)
lr2.fit(train_scaled, train_target)

print(lr2.score(train_scaled, train_target))
print(lr2.score(test_scaled, test_target))

0.9327731092436975
0.925


In [77]:
lr3 = LogisticRegression(C=10, max_iter=1000)
lr3.fit(train_scaled, train_target)

print(lr3.score(train_scaled, train_target))
print(lr3.score(test_scaled, test_target))

0.9159663865546218
0.925


In [78]:
lr3 = LogisticRegression(C=20, max_iter=5000)
lr3.fit(train_scaled, train_target)

print(lr3.score(train_scaled, train_target))
print(lr3.score(test_scaled, test_target))

0.9327731092436975
0.925


In [79]:
lr3 = LogisticRegression(C=30, max_iter=1000)
lr3.fit(train_scaled, train_target)

print(lr3.score(train_scaled, train_target))
print(lr3.score(test_scaled, test_target))

0.9663865546218487
0.925


In [81]:
print(lr.predict(test_scaled[:5]))

['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']


In [82]:
test_target[:5]

array(['Perch', 'Smelt', 'Pike', 'Whitefish', 'Perch'], dtype=object)

In [83]:
pred_value = lr.predict(test_scaled)

In [84]:
pd.Series(pred_value)

0      Perch
1      Smelt
2       Pike
3      Roach
4      Perch
5      Bream
6      Smelt
7      Roach
8      Perch
9       Pike
10     Bream
11     Perch
12     Bream
13    Parkki
14     Bream
15     Bream
16     Perch
17     Perch
18     Perch
19     Bream
20     Smelt
21     Bream
22     Bream
23     Bream
24     Bream
25     Perch
26     Perch
27     Roach
28     Smelt
29     Smelt
30      Pike
31     Perch
32     Perch
33      Pike
34     Bream
35     Perch
36     Roach
37     Roach
38    Parkki
39     Perch
dtype: object

In [85]:
pred_values_series = pd.Series(pred_value)

In [86]:
real_values_series = pd.Series(test_target)

In [87]:
real_values_series

0         Perch
1         Smelt
2          Pike
3     Whitefish
4         Perch
5         Bream
6         Smelt
7         Roach
8         Perch
9          Pike
10        Bream
11    Whitefish
12        Bream
13       Parkki
14        Bream
15        Bream
16        Perch
17        Perch
18        Perch
19        Bream
20        Smelt
21        Bream
22        Bream
23        Bream
24        Bream
25        Perch
26        Perch
27    Whitefish
28        Smelt
29        Smelt
30         Pike
31        Perch
32        Perch
33         Pike
34        Bream
35        Perch
36        Roach
37        Roach
38       Parkki
39        Perch
dtype: object

In [88]:
df1 = pd.DataFrame(pred_values_series)

In [90]:
df1['test_target'] = test_target

In [ ]:
# 93%

In [91]:
df1

0 test_target
0    Perch       Perch
1    Smelt       Smelt
2     Pike        Pike
3    Roach   Whitefish
4    Perch       Perch
5    Bream       Bream
6    Smelt       Smelt
7    Roach       Roach
8    Perch       Perch
9     Pike        Pike
10   Bream       Bream
11   Perch   Whitefish
12   Bream       Bream
13  Parkki      Parkki
14   Bream       Bream
15   Bream       Bream
16   Perch       Perch
17   Perch       Perch
18   Perch       Perch
19   Bream       Bream
20   Smelt       Smelt
21   Bream       Bream
22   Bream       Bream
23   Bream       Bream
24   Bream       Bream
25   Perch       Perch
26   Perch       Perch
27   Roach   Whitefish
28   Smelt       Smelt
29   Smelt       Smelt
30    Pike        Pike
31   Perch       Perch
32   Perch       Perch
33    Pike        Pike
34   Bream       Bream
35   Perch       Perch
36   Roach       Roach
37   Roach       Roach
38  Parkki      Parkki
39   Perch       Perch

In [95]:
1 - 3 / 39

0.9230769230769231

In [99]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Roach', 'Perch'], dtype=object)

In [98]:
np.round(lr.predict_proba(test_scaled[:5]), 2)

array([[0.  , 0.01, 0.84, 0.  , 0.13, 0.01, 0.  ],
       [0.  , 0.  , 0.04, 0.  , 0.01, 0.95, 0.  ],
       [0.  , 0.  , 0.03, 0.93, 0.02, 0.02, 0.  ],
       [0.01, 0.03, 0.31, 0.01, 0.57, 0.  , 0.08],
       [0.  , 0.  , 0.9 , 0.  , 0.09, 0.  , 0.  ]])

In [ ]:
# 4-1 확인문제
# 1. 2 / 다중 분류
# 2. 1 / 시그모이드 
# 3. 3 / 0.5