In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.13.0'

In [10]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('C:/ex/mldl/data/ThoraricSurgery3_copy.csv', header=None)

In [16]:
df.head()

0     1     2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0   1  2.88  2.16   1   0   0   0   1   1   3   0   0   0   1   0  60   0
1   2  3.40  1.88   0   0   0   0   0   0   1   0   0   0   1   0  51   0
2   2  2.76  2.08   1   0   0   0   1   0   0   0   0   0   1   0  59   0
3   2  3.68  3.04   0   0   0   0   0   0   0   0   0   0   0   0  54   0
4   2  2.44  0.96   2   0   1   0   1   1   0   0   0   0   1   0  73   1

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470 entries, 0 to 469
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       470 non-null    int64  
 1   1       470 non-null    float64
 2   2       470 non-null    float64
 3   3       470 non-null    int64  
 4   4       470 non-null    int64  
 5   5       470 non-null    int64  
 6   6       470 non-null    int64  
 7   7       470 non-null    int64  
 8   8       470 non-null    int64  
 9   9       470 non-null    int64  
 10  10      470 non-null    int64  
 11  11      470 non-null    int64  
 12  12      470 non-null    int64  
 13  13      470 non-null    int64  
 14  14      470 non-null    int64  
 15  15      470 non-null    int64  
 16  16      470 non-null    int64  
dtypes: float64(2), int64(15)
memory usage: 62.5 KB


In [17]:
from tensorflow.keras.models import Sequential

In [18]:
model = Sequential()

In [19]:
from tensorflow.keras.layers import Dense

In [20]:
df.values

array([[ 1.  ,  2.88,  2.16, ...,  0.  , 60.  ,  0.  ],
       [ 2.  ,  3.4 ,  1.88, ...,  0.  , 51.  ,  0.  ],
       [ 2.  ,  2.76,  2.08, ...,  0.  , 59.  ,  0.  ],
       ...,
       [ 2.  ,  3.04,  2.08, ...,  0.  , 52.  ,  0.  ],
       [ 2.  ,  1.96,  1.68, ...,  0.  , 79.  ,  0.  ],
       [ 2.  ,  4.72,  3.56, ...,  0.  , 51.  ,  0.  ]])

In [21]:
df.values.shape

(470, 17)

In [22]:
df.values[:, :16]

array([[ 1.  ,  2.88,  2.16, ...,  1.  ,  0.  , 60.  ],
       [ 2.  ,  3.4 ,  1.88, ...,  1.  ,  0.  , 51.  ],
       [ 2.  ,  2.76,  2.08, ...,  1.  ,  0.  , 59.  ],
       ...,
       [ 2.  ,  3.04,  2.08, ...,  0.  ,  0.  , 52.  ],
       [ 2.  ,  1.96,  1.68, ...,  1.  ,  0.  , 79.  ],
       [ 2.  ,  4.72,  3.56, ...,  1.  ,  0.  , 51.  ]])

In [23]:
X = df.values[:, :16]

In [28]:
X.shape

(470, 16)

In [25]:
y = df.values[:, 16]

In [26]:
y

array([0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0.

In [29]:
help(model.add)

Help on method add in module keras.src.engine.sequential:

add(layer) method of keras.src.engine.sequential.Sequential instance
    Adds a layer instance on top of the layer stack.
    
    Args:
        layer: layer instance.
    
    Raises:
        TypeError: If `layer` is not a layer instance.
        ValueError: In case the `layer` argument does not
            know its input shape.
        ValueError: In case the `layer` argument has
            multiple output tensors, or is already connected
            somewhere else (forbidden in `Sequential` models).



In [33]:
470 / 32

14.6875

In [31]:
model.add(Dense(30, input_dim=16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# layer = Dense(30)

In [32]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=5, batch_size=32)

Epoch 1/5
15/15 [==============================] - 0s 1ms/step - loss: 2.5229 - accuracy: 0.2277
Epoch 2/5
15/15 [==============================] - 0s 1ms/step - loss: 0.4896 - accuracy: 0.8511
Epoch 3/5
15/15 [==============================] - 0s 1ms/step - loss: 0.5711 - accuracy: 0.8511
Epoch 4/5
15/15 [==============================] - 0s 476us/step - loss: 0.4686 - accuracy: 0.8511
Epoch 5/5
15/15 [==============================] - 0s 301us/step - loss: 0.4658 - accuracy: 0.8468


In [ ]:
model.predict()