In [ ]:
# !pip install 패키지명

In [2]:
!pwd

/content


In [ ]:
!find / -name 'numpy*'

In [1]:
import numpy

In [6]:
import numpy as np

In [9]:
# help(np.array)

In [10]:
np.array([1,2,3])

array([1, 2, 3])

In [23]:
arr1= np.array([1,2,3])

In [24]:
type(arr1)

numpy.ndarray

In [25]:
arr1.shape

(3,)

In [26]:
arr1.size

3

In [17]:
arr2= np.array([[1,2,3],[4,5,6]])

In [19]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2.shape

(2, 3)

In [20]:
arr2.size

6

In [21]:
arr2.ndim

2

In [27]:
arr1.ndim

1

In [28]:
arr3= np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])

In [29]:
arr3.ndim

3

In [30]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [31]:
arr3.size

12

In [32]:
arr3.shape

(2, 2, 3)

In [33]:
arr=np.array([[1],
              [2],
              [-1.0],
              [3.14]])

In [34]:
arr

array([[ 1.  ],
       [ 2.  ],
       [-1.  ],
       [ 3.14]])

In [35]:
arr.shape

(4, 1)

In [36]:
arr.ndim

2

In [37]:
arr4=np.array([[[[1,2,-1.0,3.14]]]])

In [38]:
arr4

array([[[[ 1.  ,  2.  , -1.  ,  3.14]]]])

In [39]:
arr4.ndim

4

In [40]:
arr4.shape

(1, 1, 1, 4)

In [41]:
# 배열(numpy 배열, np.array) 계산

In [42]:
mu=np.array([1,2,3])

In [43]:
nu=np.array([4,4,4])

In [45]:
mu + nu

array([5, 6, 7])

In [46]:
(mu + nu) * 2

array([10, 12, 14])

In [47]:
# 행렬의 연산

In [48]:
A=np.array([[3,6],[4,5]])

In [49]:
A

array([[3, 6],
       [4, 5]])

In [51]:
B=np.array([[5,8],[6,7]])

In [52]:
B

array([[5, 8],
       [6, 7]])

In [53]:
A + B

array([[ 8, 14],
       [10, 12]])

In [54]:
A - B

array([[-2, -2],
       [-2, -2]])

In [56]:
C=np.array([[5,8,9],[6,7,3]])

In [57]:
A + C

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

In [58]:
np.all([True, True, True])

True

In [59]:
np.all([True, True, False])

False

In [60]:
np.any([False, False, False])

False

In [61]:
np.any([False, False, True])

True