In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
cls = np.array([95, 91,92,93,98,97,100,99]).reshape(4, 2)

In [4]:
cls

array([[ 95,  91],
       [ 92,  93],
       [ 98,  97],
       [100,  99]])

In [5]:
cls.shape

(4, 2)

In [6]:
pd.DataFrame(data=cls, columns=['A반', 'B반'])

A반  B반
0   95  91
1   92  93
2   98  97
3  100  99

In [7]:
df1 = pd.DataFrame(data=cls, columns=['A반', 'B반'])

In [9]:
df1.iloc[0]

A반    95
B반    91
Name: 0, dtype: int32

In [11]:
df1['A반']

0     95
1     92
2     98
3    100
Name: A반, dtype: int32

In [14]:
arr2d_2 = np.array([87, 85, 89, 90]).reshape(2, 2)

In [15]:
arr2d_2

array([[87, 85],
       [89, 90]])

In [16]:
df2 = pd.DataFrame(data=arr2d_2, columns=['A반', 'B반'])

In [17]:
df2

A반  B반
0  87  85
1  89  90

In [18]:
arr2d_4 = np.array([100, 100, 100, 100]).reshape(4, 1)


In [20]:
df4 = pd.DataFrame(data=arr2d_4, columns=['D반'])

In [21]:
df4

D반
0  100
1  100
2  100
3  100

In [22]:
df1.join(df4)

A반  B반   D반
0   95  91  100
1   92  93  100
2   98  97  100
3  100  99  100

In [44]:
pd.concat([df1, df2], ignore_index=True)

A반  B반
0   95  91
1   92  93
2   98  97
3  100  99
4   87  85
5   89  90

In [26]:
df1_df2 = pd.concat([df1, df2], ignore_index=True)

In [27]:
df1_df2

A반  B반
0   95  91
1   92  93
2   98  97
3  100  99
4   87  85
5   89  90

In [28]:
arr5 = np.array([10,11,12,13,14,15,16,17]).reshape(4,2)

In [29]:
arr5

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [30]:
df5 = pd.DataFrame(arr5, columns=['가', '나'])

In [31]:
df5

가   나
0  10  11
1  12  13
2  14  15
3  16  17

In [32]:
arr6 = np.array([100,100,100,100]).reshape(4,1)

In [33]:
arr6

array([[100],
       [100],
       [100],
       [100]])

In [34]:
df6 = pd.DataFrame(arr6, columns=['다'])

In [35]:
df6

다
0  100
1  100
2  100
3  100

In [36]:
df5.join(df6)

가   나    다
0  10  11  100
1  12  13  100
2  14  15  100
3  16  17  100

In [37]:
arr7 = np.array([20, 21, 22, 23]).reshape(2,2)

In [38]:
arr7

array([[20, 21],
       [22, 23]])

In [39]:
df7 = pd.DataFrame(arr7, columns=['가', '나'])

In [40]:
df7

가   나
0  20  21
1  22  23

In [42]:
pd.concat([df5, df7], ignore_index=True)

가   나
0  10  11
1  12  13
2  14  15
3  16  17
4  20  21
5  22  23

In [45]:
# 표를 만드는 일반적인 방법

In [47]:
data1 = {'id':['hang1','hang2','hang3','hang4','hang5'], 
         '이름':['홍일동','홍이동','홍삼동','홍사동','홍오동'],
         '키':[166,168,170,172,174]}

In [48]:
pd.DataFrame(data1)

id   이름    키
0  hang1  홍일동  166
1  hang2  홍이동  168
2  hang3  홍삼동  170
3  hang4  홍사동  172
4  hang5  홍오동  174

In [49]:
# 표를 만드는 일반적인 방법2

In [52]:
idx = ['hang1','hang2','hang3','hang4','hang5']

In [53]:
data2 = {'이름':['홍일동','홍이동','홍삼동','홍사동','홍오동'],
         '키':[166,168,170,172,174]}

In [54]:
pd.DataFrame(data2, index=pd.Index(idx, name='student'))

이름    키
student          
hang1    홍일동  166
hang2    홍이동  168
hang3    홍삼동  170
hang4    홍사동  172
hang5    홍오동  174

In [55]:
df_stu = pd.DataFrame(data2, index=pd.Index(idx, name='student'))

In [56]:
df_stu

이름    키
student          
hang1    홍일동  166
hang2    홍이동  168
hang3    홍삼동  170
hang4    홍사동  172
hang5    홍오동  174

In [57]:
df1_stu = pd.DataFrame(data1)

In [58]:
df1_stu.index

RangeIndex(start=0, stop=5, step=1)

In [59]:
df_stu.index

Index(['hang1', 'hang2', 'hang3', 'hang4', 'hang5'], dtype='object', name='student')

In [60]:
df1_stu.set_index('id', inplace=True)

In [61]:
df1_stu

이름    키
id             
hang1  홍일동  166
hang2  홍이동  168
hang3  홍삼동  170
hang4  홍사동  172
hang5  홍오동  174

In [62]:
df1_stu.index

Index(['hang1', 'hang2', 'hang3', 'hang4', 'hang5'], dtype='object', name='id')

In [66]:
df1_stu.loc['hang4']

이름    홍사동
키     172
Name: hang4, dtype: object

In [80]:
df2 = pd.DataFrame({'Name' : ['Harry Potter','David Baker','John Smith','Juan Martinez','Jane Connor'],
                'Gender' : ['Male','Male','Male','Male','FeMale'],
                'Age' : [23, 31, 22, 36, 30]})

In [81]:
df2

Name  Gender  Age
0   Harry Potter    Male   23
1    David Baker    Male   31
2     John Smith    Male   22
3  Juan Martinez    Male   36
4    Jane Connor  FeMale   30

In [84]:
df3 = pd.DataFrame({'Name' : ['John Smith','Alex Du Bois','Joanne Rowling','Jane Connor'],
                'Position' : ['Intern','Team Lead','Manager','Manager'],
                'Wage' : [25000, 75000, 90000, 70000]})

In [85]:
df3

Name   Position   Wage
0      John Smith     Intern  25000
1    Alex Du Bois  Team Lead  75000
2  Joanne Rowling    Manager  90000
3     Jane Connor    Manager  70000

In [96]:
pd.merge(df2, df3, on='Name', how='inner')

Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  FeMale   30  Manager  70000

In [91]:
pd.merge(df2, df3, on='Name', how='left')

Name  Gender  Age Position     Wage
0   Harry Potter    Male   23      NaN      NaN
1    David Baker    Male   31      NaN      NaN
2     John Smith    Male   22   Intern  25000.0
3  Juan Martinez    Male   36      NaN      NaN
4    Jane Connor  FeMale   30  Manager  70000.0

In [92]:
pd.merge(df2, df3, on='Name', how='right')

Name  Gender   Age   Position   Wage
0      John Smith    Male  22.0     Intern  25000
1    Alex Du Bois     NaN   NaN  Team Lead  75000
2  Joanne Rowling     NaN   NaN    Manager  90000
3     Jane Connor  FeMale  30.0    Manager  70000

In [93]:
pd.merge(df2, df3, how='outer')

Name  Gender   Age   Position     Wage
0    Alex Du Bois     NaN   NaN  Team Lead  75000.0
1     David Baker    Male  31.0        NaN      NaN
2    Harry Potter    Male  23.0        NaN      NaN
3     Jane Connor  FeMale  30.0    Manager  70000.0
4  Joanne Rowling     NaN   NaN    Manager  90000.0
5      John Smith    Male  22.0     Intern  25000.0
6   Juan Martinez    Male  36.0        NaN      NaN

In [97]:
# 엑셀에서 데이터 가져오기

In [172]:
df_1 = pd.read_excel('C:/ex/data/학생점수.xlsx',sheet_name='1학기')

In [171]:
pd.read_excel('C:/ex/data/학생점수.xlsx',sheet_name='2학기')

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [151]:
df_1.head()

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [152]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   학생      5 non-null      object
 1   국       5 non-null      int64 
 2   영       5 non-null      int64 
 3   수       5 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes


In [173]:
df_1.set_index('학생', inplace=True)

In [154]:
df_1

국   영   수
학생            
A   80  90  85
B   90  95  95
C   95  70  75
D   70  85  80
E   75  90  85

In [121]:
# 학생별 평균
for i in ['A','B','C','D','E']:
    print(i+'학생의 평균 :',np.mean(df_1.loc[i]))

A학생의 평균 : 85.0
B학생의 평균 : 93.33333333333333
C학생의 평균 : 80.0
D학생의 평균 : 78.33333333333333
E학생의 평균 : 83.33333333333333


In [157]:
df_1.transpose().describe()

학생        A          B          C          D          E
count   3.0   3.000000   3.000000   3.000000   3.000000
mean   85.0  93.333333  80.000000  78.333333  83.333333
std     5.0   2.886751  13.228757   7.637626   7.637626
min    80.0  90.000000  70.000000  70.000000  75.000000
25%    82.5  92.500000  72.500000  75.000000  80.000000
50%    85.0  95.000000  75.000000  80.000000  85.000000
75%    87.5  95.000000  85.000000  82.500000  87.500000
max    90.0  95.000000  95.000000  85.000000  90.000000

In [122]:
# 과목별 평균
for i in ['국','영','수']:
    print('과목별 평균 :',np.mean(df_1[i]))
    

과목별 평균 : 82.0
과목별 평균 : 86.0
과목별 평균 : 84.0


In [155]:
df_1.describe()

국          영          수
count   5.000000   5.000000   5.000000
mean   82.000000  86.000000  84.000000
std    10.368221   9.617692   7.416198
min    70.000000  70.000000  75.000000
25%    75.000000  85.000000  80.000000
50%    80.000000  90.000000  85.000000
75%    90.000000  90.000000  85.000000
max    95.000000  95.000000  95.000000

In [124]:
# 반 평균
print('반 평균 :',np.mean(df_1))

반 평균 : 84.0


In [125]:
# 국어 성적순 정렬
df_1['국'].sort_values()

학생
D    70
E    75
A    80
B    90
C    95
Name: 국, dtype: int64

In [158]:
df_1.sort_values(by='국')

국   영   수
학생            
D   70  85  80
E   75  90  85
A   80  90  85
B   90  95  95
C   95  70  75

In [159]:
df_1.sort_values(by='국',ascending=False)

국   영   수
학생            
C   95  70  75
B   90  95  95
A   80  90  85
E   75  90  85
D   70  85  80

In [139]:
# 학생 평균 성적 정렬
arr1 = [np.mean(df_1.loc[i]) for i in ['A','B','C','D','E']]

In [140]:
arr1.sort()
for i in arr1:
    print(i)

78.33333333333333
80.0
83.33333333333333
85.0
93.33333333333333


In [162]:
stu_mean = [df_1.loc['A'].mean(),df_1.loc['B'].mean(),df_1.loc['C'].mean(),df_1.loc['D'].mean(),df_1.loc['E'].mean()]

In [170]:
df_1

국   영   수   stu_mean
학생                       
A   80  90  85  85.000000
B   90  95  95  93.333333
C   95  70  75  80.000000
D   70  85  80  78.333333
E   75  90  85  83.333333

In [164]:
df_1['stu_mean'] = stu_mean

In [169]:
df_1

국   영   수   stu_mean
학생                       
A   80  90  85  85.000000
B   90  95  95  93.333333
C   95  70  75  80.000000
D   70  85  80  78.333333
E   75  90  85  83.333333

In [167]:
df_1.sort_values(by='stu_mean',ascending=False)

국   영   수   stu_mean
학생                       
B   90  95  95  93.333333
A   80  90  85  85.000000
E   75  90  85  83.333333
C   95  70  75  80.000000
D   70  85  80  78.333333

In [ ]:
# 데이터 요약시 유용한 피벗테이블

In [168]:
help(pd.pivot_table)

Help on function pivot_table in module pandas.core.reshape.pivot:

pivot_table(data: 'DataFrame', values=None, index=None, columns=None, aggfunc: 'AggFuncType' = 'mean', fill_value=None, margins: 'bool' = False, dropna: 'bool' = True, margins_name: 'Hashable' = 'All', observed: 'bool | lib.NoDefault' = <no_default>, sort: 'bool' = True) -> 'DataFrame'
    Create a spreadsheet-style pivot table as a DataFrame.

    The levels in the pivot table will be stored in MultiIndex objects
    (hierarchical indexes) on the index and columns of the result DataFrame.

    Parameters
    ----------
    data : DataFrame
    values : list-like or scalar, optional
        Column or columns to aggregate.
    index : column, Grouper, array, or list of the previous
        Keys to group by on the pivot table index. If a list is passed,
        it can contain any of the other types (except list). If an array is
        passed, it must be the same length as the data and will be used in
        the same man

In [175]:
df_2 = pd.read_excel('C:/ex/data/학생점수.xlsx',sheet_name='1학기').set_index('학생')

In [176]:
df_2

국   영   수
학생            
A   80  90  85
B   90  95  95
C   95  70  75
D   70  85  80
E   75  90  85

In [180]:
pd.pivot_table(df_2,index=df_2.index,aggfunc='mean')

국     수     영
학생                  
A   80.0  85.0  90.0
B   90.0  95.0  95.0
C   95.0  75.0  70.0
D   70.0  80.0  85.0
E   75.0  85.0  90.0

In [181]:
# 피벗테이블 기초

In [186]:
data = {'Date': ['2023-01-01', '2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03'], 
        'Category': ['A', 'B', 'A', 'A', 'B', 'A'], 
        'Value': [10, 20, 50, 15, 25, 10] }

In [187]:
df = pd.DataFrame(data)

In [188]:
df

Date Category  Value
0  2023-01-01        A     10
1  2023-01-01        B     20
2  2023-01-01        A     50
3  2023-01-02        A     15
4  2023-01-02        B     25
5  2023-01-03        A     10

In [190]:
pd.pivot_table(df, values='Value',index='Date', columns='Category', aggfunc='sum')

Category       A     B
Date                  
2023-01-01  60.0  20.0
2023-01-02  15.0  25.0
2023-01-03  10.0   NaN

In [ ]:
# 데이터프레임객체.통계관련메소드

In [191]:
df_stu_score = pd.read_excel('C:/ex/data/학생점수.xlsx',sheet_name='1학기')


In [192]:
df_stu_score

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [195]:
df_stu_score.drop('학생', axis=1, inplace=True)

In [197]:
df_stu_score

국   영   수
0  80  90  85
1  90  95  95
2  95  70  75
3  70  85  80
4  75  90  85

In [198]:
df_stu_score.mean(axis=0)

국    82.0
영    86.0
수    84.0
dtype: float64

In [199]:
df_stu_score.mean(axis=1)

0    85.000000
1    93.333333
2    80.000000
3    78.333333
4    83.333333
dtype: float64