In [1]:
import os
import sys
import tarfile
import time
import urllib.request

In [2]:
!pip install pyprind

In [3]:
import pyprind
import pandas as pd
import os

In [4]:
basepath = 'aclImdb'

In [5]:
labels = {'pos': 1, 'neg': 0}

In [34]:
pbar = pyprind.ProgBar(50000)
df = list([])

In [35]:
type(df)

list

In [36]:
for s in ('test', 'train'):
    for l in ('pos', 'neg'):
        path = os.path.join(basepath, s, l)
        for file in sorted(os.listdir(path)):
            with open(os.path.join(path, file),
                      'r', encoding='utf-8') as infile:
                txt = infile.read()
            df.append([txt, labels[l]])
            pbar.update()
df = pd.DataFrame(df)

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:05:38


In [37]:
df.head(3)

0  1
0  I went and saw this movie last night after bei...  1
1  Actor turned director Bill Paxton follows up h...  1
2  As a recreational golfer with some knowledge o...  1

In [38]:
df.columns = ['review', 'sentiment']

In [39]:
df.head(3)

review  sentiment
0  I went and saw this movie last night after bei...          1
1  Actor turned director Bill Paxton follows up h...          1
2  As a recreational golfer with some knowledge o...          1

In [41]:
df

review  sentiment
11841  In 1974, the teenager Martha Moxley (Maggie Gr...          1
19602  OK... so... I really like Kris Kristofferson a...          0
45519  ***SPOILER*** Do not read this, if you think a...          0
25747  hi for all the people who have seen this wonde...          1
42642  I recently bought the DVD, forgetting just how...          0
...                                                  ...        ...
21243  OK, lets start with the best. the building. al...          0
45891  The British 'heritage film' industry is out of...          0
42613  I don't even know where to begin on this one. ...          0
43567  Richard Tyler is a little boy who is scared of...          0
2732   I waited long to watch this movie. Also becaus...          1

[50000 rows x 2 columns]

In [40]:
import numpy as np

np.random.seed(0)
df = df.reindex(np.random.permutation(df.index))

In [43]:
df.to_csv('movie_data.csv', index=False, encoding='utf-8')

In [44]:
import pandas as pd

df = pd.read_csv('movie_data.csv', encoding='utf-8')
df.head(3)

review  sentiment
0  In 1974, the teenager Martha Moxley (Maggie Gr...          1
1  OK... so... I really like Kris Kristofferson a...          0
2  ***SPOILER*** Do not read this, if you think a...          0

In [45]:
df.shape

(50000, 2)

## 8.2 BoW 모델 소개

### 8.2.1 단어를 특성 벡터로 변환

CountVectorizer의 fit_transform 메서드를 호출하여 BoW 모델의 어휘사전을 만들고 다음 세 문장을 희소한 특성 벡터로 변환합니다:

In [46]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer()
docs = np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining, the weather is sweet, and one and one is two'])
bag = count.fit_transform(docs)

어휘 사전의 내용을 출력해 보면 BoW 모델의 개념을 이해하는 데 도움이 됩니다:

In [47]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [48]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


In [49]:
count.vocabulary_

{'the': 6,
 'sun': 4,
 'is': 1,
 'shining': 3,
 'weather': 8,
 'sweet': 5,
 'and': 0,
 'one': 2,
 'two': 7}

In [50]:
bag

<3x9 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [51]:
bag.toarray()

array([[0, 1, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 1],
       [2, 3, 2, 1, 1, 1, 2, 1, 1]], dtype=int64)

### 8.2.2 tf-idf를 사용하여 단어 적합성 평가

In [52]:
np.set_printoptions(precision=2)

In [53]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer(use_idf=True,
                         norm='l2',
                         smooth_idf=True)
print(tfidf.fit_transform(count.fit_transform(docs))
      .toarray())

[[0.   0.43 0.   0.56 0.56 0.   0.43 0.   0.  ]
 [0.   0.43 0.   0.   0.   0.56 0.43 0.   0.56]
 [0.5  0.45 0.5  0.19 0.19 0.19 0.3  0.25 0.19]]


In [54]:

tf_is = 3
n_docs = 3
idf_is = np.log((n_docs+1) / (3+1))
tfidf_is = tf_is * (idf_is + 1)
print('tf-idf of term "is" = %.2f' % tfidf_is)

tf-idf of term "is" = 3.00


In [55]:
tfidf = TfidfTransformer(use_idf=True, norm=None, smooth_idf=True)
raw_tfidf = tfidf.fit_transform(count.fit_transform(docs)).toarray()[-1]
raw_tfidf

array([3.39, 3.  , 3.39, 1.29, 1.29, 1.29, 2.  , 1.69, 1.29])

In [56]:
l2_tfidf = raw_tfidf / np.sqrt(np.sum(raw_tfidf**2))
l2_tfidf

array([0.5 , 0.45, 0.5 , 0.19, 0.19, 0.19, 0.3 , 0.25, 0.19])

### 8.2.3 텍스트 데이터 정제

In [57]:
df.loc[0, 'review'][-50:]

'is seven.<br /><br />Title (Brazil): Not Available'

In [58]:
import re
def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)',
                           text)
    text = (re.sub('[\W]+', ' ', text.lower()) +
            ' '.join(emoticons).replace('-', ''))
    return text

In [59]:

preprocessor(df.loc[0, 'review'][-50:])

'is seven title brazil not available'

In [60]:
preprocessor("</a>This :) is :( a test :-)!")

'this is a test :) :( :)'

In [61]:
df['review'] = df['review'].apply(preprocessor)

In [62]:
df['review'].head()

0    in 1974 the teenager martha moxley maggie grac...
1    ok so i really like kris kristofferson and his...
2     spoiler do not read this if you think about w...
3    hi for all the people who have seen this wonde...
4    i recently bought the dvd forgetting just how ...
Name: review, dtype: object

### 8.2.4 문서를 토큰으로 나누기

In [63]:
from nltk.stem.porter import PorterStemmer

In [64]:
porter = PorterStemmer()

In [65]:
def tokenizer(text):
    return text.split()

In [66]:
def tokenizer_porter(text):
    return [porter.stem(word) for word in text.split()]

In [67]:
tokenizer('runners like running and thus they run')

['runners', 'like', 'running', 'and', 'thus', 'they', 'run']

In [69]:
tokenizer_porter('runners like running and thus they run')

['runner', 'like', 'run', 'and', 'thu', 'they', 'run']

In [70]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ysj\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [71]:
from nltk.corpus import stopwords

stop = stopwords.words('english')
[w for w in tokenizer_porter('a runner likes running and runs a lot')[-10:]
if w not in stop]

['runner', 'like', 'run', 'run', 'lot']