In [1]:
import cv2
import numpy as np

In [3]:
img = cv2.imread('./img/girl.jpg')

In [4]:
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
img.shape

(293, 406, 3)

In [6]:
cv2.split(img) # b, g, r

(array([[ 52,  47,  39, ...,  24,  31,  35],
        [ 51,  47,  39, ...,  26,  32,  35],
        [ 51,  46,  39, ...,  28,  33,  35],
        ...,
        [ 29,  38,  47, ..., 218, 221, 222],
        [ 28,  37,  47, ..., 218, 222, 224],
        [ 25,  36,  46, ..., 223, 226, 229]], dtype=uint8),
 array([[ 71,  68,  69, ...,  72,  76,  80],
        [ 70,  68,  69, ...,  74,  77,  80],
        [ 70,  67,  69, ...,  77,  78,  80],
        ...,
        [ 95, 104, 115, ..., 190, 191, 192],
        [ 94, 104, 117, ..., 190, 192, 194],
        [ 92, 103, 116, ..., 193, 196, 199]], dtype=uint8),
 array([[ 76,  70,  64, ...,  54,  59,  63],
        [ 75,  70,  64, ...,  56,  60,  63],
        [ 73,  68,  64, ...,  57,  61,  63],
        ...,
        [ 66,  75,  84, ..., 203, 202, 203],
        [ 65,  75,  86, ..., 203, 203, 205],
        [ 63,  74,  85, ..., 206, 207, 210]], dtype=uint8))

In [7]:
b,g,r = cv2.split(img)

In [9]:
(b+g+r) / 3

array([[66.33333333, 61.66666667, 57.33333333, ..., 50.        ,
        55.33333333, 59.33333333],
       [65.33333333, 61.66666667, 57.33333333, ..., 52.        ,
        56.33333333, 59.33333333],
       [64.66666667, 60.33333333, 57.33333333, ..., 54.        ,
        57.33333333, 59.33333333],
       ...,
       [63.33333333, 72.33333333, 82.        , ..., 33.        ,
        34.        , 35.        ],
       [62.33333333, 72.        , 83.33333333, ..., 33.        ,
        35.        , 37.        ],
       [60.        , 71.        , 82.33333333, ..., 36.66666667,
        39.        , 42.        ]])

In [10]:
result = (b+g+r) / 3

In [11]:
result.dtype

dtype('float64')

In [13]:
result.shape

(293, 406)

In [12]:
cv2.imshow('result', result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
gray1 = ((b+g+r) / 3).astype(np.uint8)

In [15]:
gray1.shape

(293, 406)

In [16]:
gray1

array([[66, 61, 57, ..., 50, 55, 59],
       [65, 61, 57, ..., 52, 56, 59],
       [64, 60, 57, ..., 54, 57, 59],
       ...,
       [63, 72, 82, ..., 33, 34, 35],
       [62, 72, 83, ..., 33, 35, 37],
       [60, 71, 82, ..., 36, 39, 42]], dtype=uint8)

In [17]:
cv2.imshow('gray1', gray1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
gray2 = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

In [19]:
cv2.imshow('gray2', gray2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2
import numpy as np

img = cv2.imread('./img/girl.jpg')

# dtpye을 uint8에서 uint16으로 바꾼 이유는 uint8을 평균값을 구하는 과정에서
# 3채널의 값을 합하면 255(uint8의 최댓값)보다 큰 값이 나올 수 있으므로 uint16으로 변경해서 계산을 
# 마친 후 다시 astype으로 dtype을 변경한다

img2 = img.astype(np.uint16)                # dtype 변경 ---①
b,g,r = cv2.split(img2)                     # 채널 별로 분리 ---②
#b,g,r = img2[:,:,0], img2[:,:,1], img2[:,:,2]
gray1 = ((b + g + r)/3).astype(np.uint8)    # 평균 값 연산후 dtype 변경 ---③

gray2 = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # BGR을 그레이 스케일로 변경 ---④
cv2.imshow('original', img)
cv2.imshow('gray1', gray1)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
import cv2
import numpy as np

img = cv2.imread('./img/girl.jpg')

# img2 = img.astype(np.uint16)                # dtype 변경 ---①
b,g,r = cv2.split(img)                     # 채널 별로 분리 ---②
#b,g,r = img2[:,:,0], img2[:,:,1], img2[:,:,2]
gray1 = ((b + g + r)/3).astype(np.uint8)    # 평균 값 연산후 dtype 변경 ---③

gray2 = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # BGR을 그레이 스케일로 변경 ---④
cv2.imshow('original', img)
cv2.imshow('gray1', gray1)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
img = cv2.imread('./img/girl.jpg')


In [23]:
img.dtype

dtype('uint8')

In [24]:
img = cv2.imread('./img/girl.jpg')
b,g,r = cv2.split(img)

In [25]:
b+g+r

array([[199, 185, 172, ..., 150, 166, 178],
       [196, 185, 172, ..., 156, 169, 178],
       [194, 181, 172, ..., 162, 172, 178],
       ...,
       [190, 217, 246, ...,  99, 102, 105],
       [187, 216, 250, ...,  99, 105, 111],
       [180, 213, 247, ..., 110, 117, 126]], dtype=uint8)

In [27]:
b

array([[ 52,  47,  39, ...,  24,  31,  35],
       [ 51,  47,  39, ...,  26,  32,  35],
       [ 51,  46,  39, ...,  28,  33,  35],
       ...,
       [ 29,  38,  47, ..., 218, 221, 222],
       [ 28,  37,  47, ..., 218, 222, 224],
       [ 25,  36,  46, ..., 223, 226, 229]], dtype=uint8)

In [29]:
g

array([[ 71,  68,  69, ...,  72,  76,  80],
       [ 70,  68,  69, ...,  74,  77,  80],
       [ 70,  67,  69, ...,  77,  78,  80],
       ...,
       [ 95, 104, 115, ..., 190, 191, 192],
       [ 94, 104, 117, ..., 190, 192, 194],
       [ 92, 103, 116, ..., 193, 196, 199]], dtype=uint8)

In [30]:
b+g

array([[123, 115, 108, ...,  96, 107, 115],
       [121, 115, 108, ..., 100, 109, 115],
       [121, 113, 108, ..., 105, 111, 115],
       ...,
       [124, 142, 162, ..., 152, 156, 158],
       [122, 141, 164, ..., 152, 158, 162],
       [117, 139, 162, ..., 160, 166, 172]], dtype=uint8)

In [31]:
229+199

428

In [34]:
428 - 256

172

In [26]:
print(np.max(b+g+r))
print(np.min(b+g+r))

255
0


In [36]:
# uint8 -> uint16으로 타입 변환
img = cv2.imread('./img/girl.jpg')
img2 = img.astype(np.uint16)
b,g,r = cv2.split(img2)

In [37]:
b + g

array([[123, 115, 108, ...,  96, 107, 115],
       [121, 115, 108, ..., 100, 109, 115],
       [121, 113, 108, ..., 105, 111, 115],
       ...,
       [124, 142, 162, ..., 408, 412, 414],
       [122, 141, 164, ..., 408, 414, 418],
       [117, 139, 162, ..., 416, 422, 428]], dtype=uint16)