In [1]:
import sys
import numpy as np
import cv2

In [2]:
src = cv2.imread('./img/pepper.bmp', cv2.IMREAD_COLOR)

In [3]:
src_ycrcb = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)

In [4]:
ycrcb_planes = cv2.split(src_ycrcb)

In [6]:
ycrcb_planes

(array([[ 30,  58,  62, ...,  75,  81,  57],
        [ 37, 119, 114, ..., 174, 161, 157],
        [ 38, 121, 115, ..., 171, 170, 158],
        ...,
        [ 28, 124, 132, ..., 199, 196, 187],
        [ 28, 121, 111, ..., 195, 193, 169],
        [ 28,  86, 127, ..., 184, 192, 196]], dtype=uint8),
 array([[179, 186, 191, ..., 211, 216, 173],
        [189, 179, 182, ..., 114, 110,  98],
        [191, 174, 178, ..., 109, 112,  96],
        ...,
        [174, 130, 131, ..., 115, 114, 129],
        [174, 143, 139, ..., 114, 116, 147],
        [174, 152, 137, ..., 115, 113, 129]], dtype=uint8),
 array([[111, 175, 175, ..., 175, 182, 198],
        [107,  87,  92, ...,  78,  86,  87],
        [107,  88,  90, ...,  83,  76,  88],
        ...,
        [112,  85,  84, ..., 114, 113,  95],
        [112,  89,  92, ..., 110, 115,  99],
        [112, 100,  89, ..., 109, 122, 114]], dtype=uint8))

In [7]:
y = ycrcb_planes[0]

In [8]:
y.shape

(512, 512)

In [13]:
y = cv2.equalizeHist(ycrcb_planes[0]) 

In [14]:
dst_ycrcb = cv2.merge([y, ycrcb_planes[1], ycrcb_planes[2]])

In [15]:
dst_ycrcb

array([[[ 20, 179, 111],
        [ 36, 186, 175],
        [ 39, 191, 175],
        ...,
        [ 51, 211, 175],
        [ 60, 216, 182],
        [ 35, 173, 198]],

       [[ 23, 189, 107],
        [126, 179,  87],
        [121, 182,  92],
        ...,
        [205, 114,  78],
        [183, 110,  86],
        [176,  98,  87]],

       [[ 23, 191, 107],
        [128, 174,  88],
        [122, 178,  90],
        ...,
        [200, 109,  83],
        [199, 112,  76],
        [178,  96,  88]],

       ...,

       [[ 18, 174, 112],
        [131, 130,  85],
        [139, 131,  84],
        ...,
        [244, 115, 114],
        [242, 114, 113],
        [227, 129,  95]],

       [[ 18, 174, 112],
        [128, 143,  89],
        [118, 139,  92],
        ...,
        [241, 114, 110],
        [238, 116, 115],
        [197, 147,  99]],

       [[ 18, 174, 112],
        [ 69, 152, 100],
        [134, 137,  89],
        ...,
        [221, 115, 109],
        [237, 113, 122],
        [242, 129, 114]]

In [16]:
dst = cv2.cvtColor(dst_ycrcb, cv2.COLOR_YCrCb2BGR)

In [17]:
cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
import numpy as np
import cv2

In [63]:
# Calculate CrCb histogram from a reference image

ref = cv2.imread('./img/ref.png', cv2.IMREAD_COLOR)
mask = cv2.imread('./img/mask.bmp', cv2.IMREAD_GRAYSCALE)
ref_ycrcb = cv2.cvtColor(ref, cv2.COLOR_BGR2YCrCb)

In [64]:
print(ref.shape, mask.shape)

(480, 720, 3) (480, 720)


In [71]:
mask

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
channels = [1, 2]
cr_bins = 128
cb_bins = 128
histSize = [cr_bins, cb_bins]
cr_range = [0, 256]
cb_range = [0, 256]
ranges = cr_range + cb_range

In [24]:
hist = cv2.calcHist([ref_ycrcb], channels, mask, histSize, ranges)

In [27]:
type(hist)

numpy.ndarray

In [25]:
# Apply histogram backprojection to an input image

src = cv2.imread('./img/kids.png', cv2.IMREAD_COLOR)
src_ycrcb = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)

backproj = cv2.calcBackProject([src_ycrcb], channels, hist, ranges, 1)

In [26]:
cv2.imshow('src', src)
cv2.imshow('backproj', backproj)
cv2.waitKey()
cv2.destroyAllWindows()


### practice

In [1]:
import numpy as np
import cv2

In [2]:
ref = cv2.imread('./img/pcb.jpg', cv2.IMREAD_COLOR)
ref_ycrcb = cv2.cvtColor(ref, cv2.COLOR_BGR2YCrCb)

In [3]:
channels = [1, 2]
cr_bins = 128
cb_bins = 128
histSize = [cr_bins, cb_bins]
cr_range = [0, 256]
cb_range = [0, 256]
ranges = cr_range + cb_range

In [4]:
ref.shape

(2159, 2775, 3)

In [5]:
ref.shape[0:2]

(2159, 2775)

In [6]:
mask = np.zeros(ref.shape[0:2])

In [7]:
# 타입 변경 필수
mask = mask.astype(np.uint8)

In [8]:
mask[200:400, 200:400] = 255

In [9]:
cv2.imshow('mask', mask)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
hist = cv2.calcHist([ref_ycrcb], channels, mask, histSize, ranges)

In [11]:
cv2.imshow('hist', hist)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
# Apply histogram backprojection to an input image

src = cv2.imread('./img/pcb.jpg', cv2.IMREAD_COLOR)
src_ycrcb = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)

backproj = cv2.calcBackProject([src_ycrcb], channels, hist, ranges, 1)

In [13]:
src = cv2.resize(src, (800, 600))
backproj = cv2.resize(backproj, (800, 600))

In [14]:
cv2.imshow('src', src)
cv2.imshow('backproj', backproj)
cv2.waitKey()
cv2.destroyAllWindows()
