In [9]:
import numpy as np
import cv2

In [10]:
def labeling_basic():
    src = np.array([[0, 0, 1, 1, 0, 0, 0, 0],
                    [1, 1, 1, 1, 0, 0, 1, 0],
                    [1, 1, 1, 1, 0, 0, 0, 0],
                    [0, 0, 0, 0, 0, 1, 1, 0],
                    [0, 0, 0, 1, 1, 1, 1, 0],
                    [0, 0, 0, 1, 0, 0, 1, 0],
                    [0, 0, 1, 1, 1, 1, 1, 0],
                    [0, 0, 0, 0, 0, 0, 0, 0]]).astype(np.uint8)
    
    src = src * 255

    cnt, labels = cv2.connectedComponents(src)

    print('src:'), 
    print(src)
    print('labels:')
    print(labels)
    print('number of labels:', cnt)

In [12]:
def labeling_stats():
    src = cv2.imread('./img/keyboard.bmp', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    _, src_bin = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

    cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(src_bin)

    dst = cv2.cvtColor(src, cv2.COLOR_GRAY2BGR)

    for i in range(1, cnt):
        (x, y, w, h, area) = stats[i]

        if area < 20:
            continue

        pt1 = (x, y)
        pt2 = (x + w, y + h)
        cv2.rectangle(dst, pt1, pt2, (0, 255, 255))
    
    cv2.imshow('src', src)
    cv2.imshow('dst', dst)

    cv2.waitKey()
    cv2.destroyAllWindows()

In [13]:
labeling_basic()

src:
[[  0   0 255 255   0   0   0   0]
 [255 255 255 255   0   0 255   0]
 [255 255 255 255   0   0   0   0]
 [  0   0   0   0   0 255 255   0]
 [  0   0   0 255 255 255 255   0]
 [  0   0   0 255   0   0 255   0]
 [  0   0 255 255 255 255 255   0]
 [  0   0   0   0   0   0   0   0]]
labels:
[[0 0 1 1 0 0 0 0]
 [1 1 1 1 0 0 2 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 0 3 3 0]
 [0 0 0 3 3 3 3 0]
 [0 0 0 3 0 0 3 0]
 [0 0 3 3 3 3 3 0]
 [0 0 0 0 0 0 0 0]]
number of labels: 4


In [14]:
labeling_stats()

cnt labels stats 38 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[     0      0    512    512 256750]
 [   102     30     23     29    341]
 [   276     32     23     27    259]
 [   451     36      9     36    168]
 [   278     45      1      1      1]
 [   102     95     21     33    230]
 [   274     97     21     34    373]
 [   445     99     21     34    366]
 [   387    149      1      1      1]
 [    16    198     34     38    350]
 [   189    200     29     38    452]
 [   370    201      8     38    221]
 [   197    253      1      1      1]
 [   271    258     14     40    245]
 [   441    260     14     40    239]
 [    78    272     36     25    313]
 [   135    310      1      1      1]
 [   302    312      1      1      1]
 [   470    314      1      2      2]
 [   121    320      1      1      1]
 [   247    320      1      1      1]
 [   283    331      1      1      1]
 [    60    365     29  

### practice

In [27]:
import numpy as np
import cv2

In [58]:
img = cv2.imread('./img/pcb.jpg', cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (800, 600), interpolation=cv2.INTER_LANCZOS4)

In [31]:
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [59]:
_, img_bin = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

In [35]:
cv2.imshow('img_bin', img_bin)
cv2.waitKey()
cv2.destroyAllWindows()

In [60]:
cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(img_bin)

In [61]:
dst = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

In [62]:
for i in range(1, cnt):
    (x, y, w, h, area) = stats[i]

    if area < 40:
        continue

    pt1 = (x, y)
    pt2 = (x + w, y + h)
    cv2.rectangle(dst, pt1, pt2, (0, 255, 255))
    
cv2.imshow('img', img)
cv2.imshow('dst', dst)

cv2.waitKey()
cv2.destroyAllWindows()

In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('./img/PCB-Manufacturing-Defects.png', cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (750, 375), interpolation=cv2.INTER_LANCZOS4)
img2 = cv2.imread('./img/PCB-Manufacturing-Defects.png')
img2 = cv2.resize(img2, (750, 375), interpolation=cv2.INTER_LANCZOS4)
hsv = cv2.cvtColor(img2, cv2.COLOR_BGR2HSV)

In [3]:
cv2.imshow('img', img)
cv2.imshow('img2', img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
red1 = np.array([0, 0, 0])
red2 = np.array([20, 255,255])
red3 = np.array([160, 0, 0])
red4 = np.array([180, 255,255])

mask_red = cv2.inRange(hsv, red1, red2)
mask_red2 = cv2.inRange(hsv, red3, red4)

res_red1 = cv2.bitwise_and(img2, img2, mask=mask_red)
res_red2 = cv2.bitwise_and(img2, img2, mask=mask_red2)
res_red = cv2.bitwise_or(res_red1, res_red2)

In [5]:
res_red = cv2.cvtColor(res_red, cv2.COLOR_BGR2GRAY)

In [6]:
_, res_red = cv2.threshold(res_red, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

In [7]:
_, img_bin = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

In [12]:
cv2.imshow('img_bin', img_bin)
cv2.imshow('res_green', res_red)
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(res_red)

In [10]:
dst = img2.copy()

In [96]:
# cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(img_bin)

In [73]:
# dst = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

In [11]:
for i in range(1, cnt):
    (x, y, w, h, area) = stats[i]

    if area < 20:
        continue

    pt1 = (x, y)
    pt2 = (x + w, y + h)
    cv2.rectangle(dst, pt1, pt2, (0, 255, 255))
    
cv2.imshow('img', img)
cv2.imshow('dst', dst)

cv2.waitKey()
cv2.destroyAllWindows()