In [1]:
import sys
import numpy as np
import cv2

In [5]:
img = cv2.imread('./img/circuit.bmp', cv2.IMREAD_COLOR)
templ = cv2.imread('./img/crystal.bmp', cv2.IMREAD_COLOR)

In [12]:
img2 = cv2.add(img, (50, 50, 50))

In [13]:
cv2.imshow('img', img)
cv2.imshow('img2', img2)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
noise = np.zeros(img.shape, np.int32)
cv2.randn(noise, 0, 10)
img = cv2.add(img, noise, dtype=cv2.CV_8UC3)

In [15]:
res = cv2.matchTemplate(img, templ, cv2.TM_CCOEFF_NORMED)
res_norm = cv2.normalize(res, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

In [16]:
_, maxv, _, maxloc = cv2.minMaxLoc(res)
print('maxv:', maxv)

maxv: 0.9956192970275879


In [17]:
(th, tw) = templ.shape[:2]
cv2.rectangle(img, maxloc, (maxloc[0] + tw, maxloc[1] + th), (0, 0, 255), 2)

array([[[ 55,  62,  12],
        [ 52,  60,  12],
        [ 47,  56,   9],
        ...,
        [ 68,  77,  62],
        [ 76,  77,  60],
        [ 64,  80,  60]],

       [[ 45,  62,  12],
        [ 61,  63,  14],
        [ 51,  62,  11],
        ...,
        [104, 149, 155],
        [103, 149, 152],
        [108, 147, 148]],

       [[ 68,  63,  15],
        [ 59,  63,  11],
        [ 49,  63,  12],
        ...,
        [110, 174, 187],
        [116, 170, 185],
        [109, 171, 185]],

       ...,

       [[ 67,  74,  10],
        [ 65,  71,   6],
        [ 68,  72,  13],
        ...,
        [145, 156, 173],
        [140, 133, 146],
        [116, 110, 125]],

       [[ 62,  77,  13],
        [ 48,  73,   8],
        [ 65,  76,  17],
        ...,
        [255, 255, 255],
        [145, 167, 185],
        [ 75, 104, 136]],

       [[ 56,  72,  10],
        [ 73,  77,  14],
        [ 58,  77,  18],
        ...,
        [156, 138, 162],
        [ 80,  82, 104],
        [ 75,  71,  97]]

In [18]:
cv2.imshow('templ', templ)
cv2.imshow('res_norm', res_norm)
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [26]:
import sys
import numpy as np
import cv2

In [40]:
img = cv2.imread('./img/00041000_test.jpg', cv2.IMREAD_COLOR)
templ = cv2.imread('./img/defect_00041000_8.jpg', cv2.IMREAD_COLOR)

In [41]:
noise = np.zeros(img.shape, np.int32)
cv2.randn(noise, 0, 10)
img = cv2.add(img, noise, dtype=cv2.CV_8UC3)

In [42]:
res = cv2.matchTemplate(img, templ, cv2.TM_CCOEFF_NORMED)
res_norm = cv2.normalize(res, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

In [43]:
_, maxv, _, maxloc = cv2.minMaxLoc(res)
print('maxv:', maxv)

maxv: 0.9994532465934753


In [44]:
(th, tw) = templ.shape[:2]
cv2.rectangle(img, maxloc, (maxloc[0] + tw, maxloc[1] + th), (0, 0, 255), 2)

array([[[  4,   0,   0],
        [  9,   0,   0],
        [  0,   0,   0],
        ...,
        [  2,   0,   0],
        [  4,   0,   0],
        [  8,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [ 15,   0,   0],
        ...,
        [  5,   0,   0],
        [  0,   0,   0],
        [ 16,   0,   0]],

       [[  0,   0,   0],
        [  3,   0,   0],
        [  8,   0,   0],
        ...,
        [  0,   0,   0],
        [ 15,   0,   0],
        [  0,   0,   0]],

       ...,

       [[255, 255, 255],
        [252, 255, 255],
        [254, 255, 255],
        ...,
        [236, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [249, 255, 255],
        [248, 255, 255],
        ...,
        [246, 255, 255],
        [255, 255, 255],
        [246, 255, 255]],

       [[255, 255, 255],
        [242, 255, 255],
        [255, 255, 255],
        ...,
        [249, 255, 255],
        [254, 255, 255],
        [252, 255, 255]]

In [45]:
cv2.imshow('templ', templ)
cv2.imshow('res_norm', res_norm)
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

In [30]:
import sys
import numpy as np
import cv2

In [31]:
img = cv2.imread('./img/01_missing_hole_01.jpg', cv2.IMREAD_COLOR)
img.shape

(1586, 3034, 3)

In [32]:
img = cv2.resize(img, (600, 300))

In [33]:
print(int(2459 * (600 / 3034)), int(2530 * (600 / 3034)), int(1274 * (300 / 1586)), int(1329 * (300 / 1586)))

486 500 240 251


In [34]:
templ = img[240:251, 486:500, :]

In [35]:
cv2.imshow('img', img)
cv2.imshow('templ', templ)
cv2.waitKey()
cv2.destroyAllWindows()

In [36]:
noise = np.zeros(img.shape, np.int32)
cv2.randn(noise, 0, 10)
img = cv2.add(img, noise, dtype=cv2.CV_8UC3)

In [37]:
res = cv2.matchTemplate(img, templ, cv2.TM_CCOEFF_NORMED)
res_norm = cv2.normalize(res, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

In [38]:
_, maxv, _, maxloc = cv2.minMaxLoc(res)
print('maxv:', maxv)

maxv: 0.9902377724647522


In [39]:
(th, tw) = templ.shape[:2]
cv2.rectangle(img, maxloc, (maxloc[0] + tw, maxloc[1] + th), (0, 0, 255), 2)

array([[[124, 141, 151],
        [131, 140, 149],
        [153, 139, 149],
        ...,
        [161, 149, 156],
        [160, 150, 156],
        [141, 148, 154]],

       [[117, 136, 146],
        [131, 140, 151],
        [144, 137, 147],
        ...,
        [160, 148, 153],
        [135, 150, 156],
        [155, 152, 158]],

       [[123, 134, 144],
        [131, 133, 143],
        [134, 137, 144],
        ...,
        [142, 150, 154],
        [153, 148, 153],
        [159, 149, 154]],

       ...,

       [[132, 141, 147],
        [123, 134, 140],
        [133, 136, 143],
        ...,
        [138, 143, 145],
        [162, 147, 150],
        [154, 149, 151]],

       [[146, 138, 145],
        [153, 136, 143],
        [167, 138, 145],
        ...,
        [153, 150, 155],
        [165, 146, 151],
        [160, 150, 155]],

       [[159, 137, 143],
        [140, 137, 143],
        [148, 137, 144],
        ...,
        [156, 146, 151],
        [163, 152, 157],
        [163, 146, 151]]

In [40]:
cv2.imshow('templ', templ)
cv2.imshow('res_norm', res_norm)
cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()